var firstName = ("tanzeel");
console.log(firstName);
var lastName = ("qamar");
console.log(lastName);
var part1 = (2021);
var part2 = (2024);
var result = (part1 + part2);
console.log(result);
// now another method for variables
var elderSibling = ("tanzeel");
console.log(elderSibling);
var youngerSibling = ("fareeba");
console.log(youngerSibling);
var ageofelderSibling = (22);
console.log(ageofelderSibling);
var ageofyoungerSibling = (18);
console.log(ageofyoungerSibling);
var areStudying = (true);
console.log(areStudying);
var totalStudents = (500);
var absentStudents = (127);
console.log(totalStudents - absentStudents);
var mangoesin1Carton = (24);
var mangoesin50Cartons = (50);
console.log(mangoesin1Carton * mangoesin50Cartons);
var totalGifts = (45);
console.log("totalGifts=45");
var numberofChildren = (15);
console.log("numberofChildren=");
var num = (250);
console.log("45/15");
console.log(totalGifts / numberofChildren);
var sweaters = (250);
console.log(sweaters = 250);
console.log("sweatrs we have=250");
console.log("distributed to 4 groups");
var distributedtoGroups = (4);
console.log("How many sweaters left?");
console.log(sweaters % distributedtoGroups);
console.log("each group will have");
console.log(sweaters / distributedtoGroups);
// this coding contains variables (string, number and boolean) also arithematic operators(addition, subtraction, multiplication, division and modulus)
