let firstName = ("tanzeel");
console.log(firstName);
let lastName = ("qamar");
console.log (lastName);
let part1 =(2021);
let part2 =(2024);
let result = (part1 + part2);
console.log(result);
// now another method for variables
let elderSibling: string = ("tanzeel");
console.log(elderSibling);
let youngerSibling:string=("fareeba");
console.log(youngerSibling);
let ageofelderSibling:number=(22);
console.log(ageofelderSibling);
let ageofyoungerSibling:number=(18);
console.log(ageofyoungerSibling);
let areStudying:boolean=(true);
console.log(areStudying);
let totalStudents:number=(500);
let absentStudents:number=(127);
console.log(totalStudents-absentStudents);
let mangoesin1Carton:number=(24);
let mangoesin50Cartons=(50);
console.log(mangoesin1Carton*mangoesin50Cartons);
let totalGifts=(45);
console.log("totalGifts=45");
let numberofChildren=(15);
console.log("numberofChildren=");let num=(250);
console.log("45/15");
console.log(totalGifts/numberofChildren);
let sweaters=(250);
console.log(sweaters=250);
console.log("sweatrs we have=250");
console.log("distributed to 4 groups");
let distributedtoGroups=(4);
console.log("How many sweaters left?");
console.log(sweaters%distributedtoGroups);
console.log("each group will have");
console.log(sweaters/distributedtoGroups);
// this coding contains variables (string, number and boolean) also arithematic operators(addition, subtraction, multiplication, division and modulus)